name: Feature or task request
about: Propose a new capability, planned task, or phase-aligned implementation work
labels: [enhancement]
body:
  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: What capability or task should be added?
      placeholder: Describe desired outcome and user/system impact
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope and boundaries
      description: What is in scope and out of scope?
      placeholder: In scope / Out of scope
    validations:
      required: true

  - type: dropdown
    id: phase
    attributes:
      label: Roadmap phase
      description: Map this request to a roadmap phase
      options:
        - Phase 1: Core State Machine
        - Phase 2: Governance Engine
        - Phase 3: Orchestration Foundation
        - Cross-cutting: Issue Operations
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Suggested priority
      description: Use triage matrix from docs/issue-triage.md
      options:
        - P0
        - P1
        - P2
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: How do we know this is complete?
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies / related issues (optional)
      description: Link RFCs, issues, or external dependencies if any
